<?php

declare(strict_types=1);

use App\Application\Handlers\AuthHandler;
use App\Application\Handlers\HandlerInterface;
use App\Application\Handlers\HomeHandler;

/**
 * WARNING: This file is automatically generated
 * from protobuf definitions. Do not edit manually.
 *
 * @return array<array{
 *     method: string,
 *     path: string,
 *     handler: class-string<HandlerInterface>
 * }>
 */
return [
    // AuthService.Login
    [
        'method' => 'POST',
        'path' => '/api/v1/auth/login',
        'handler' => AuthHandler::class,
    ],
    // AuthService.Logout
    [
        'method' => 'POST',
        'path' => '/api/v1/auth/logout',
        'handler' => AuthHandler::class,
    ],
    // AuthService.RefreshToken
    [
        'method' => 'POST',
        'path' => '/api/v1/auth/refresh',
        'handler' => AuthHandler::class,
    ],
    // HomeService.Home
    [
        'method' => 'GET',
        'path' => '/api/v1/home',
        'handler' => HomeHandler::class,
    ],
];
